### ISSUE TITLE
Using with the Spock framework

### ISSUE THREAD

**Issue by spartanhooah** [webcompere/system-stubs#33]
I'm converting a project from Spock 1.3 to 2.0, which requires migrating from JUnit 4 dependencies to JUnit 5. We made use of Stefan Birkner's `system-rules` library, and this seemed like a handy replacement. However, I can't get the environment variables to work anymore. I have tried adding in this library like so:

```
@SpringBootTest
@ExtendWith(SystemStubsExtension.class)
class ServiceTest extends Specification {
    @Shared
    @SystemStub
    static final EnvironmentVariables environmentVariables = new EnvironmentVariables().set("KAFKA_RUNTIME_ENV", "dev")
    
    // unit tests follow
}
```

However, the system is not picking up the `KAFKA_RUNTIME_ENV` variable:
`Unable to determine Environment through Environment Variable, ensure that one of the following is set: KAFKA_RUNTIME_ENV, ENVIRONMENT`

What am I missing?

**Comment by ashleyfrieze** [comment]
@spartanhooah - great question.

Here's the thing. The Annotation `@SpringBootTest` is processed BEFORE the SystemStubsExtension is able to _turn on_ the environment variable.

In this situation, I would normally use `@Nested` classes.

See the example here - https://github.com/webcompere/system-stubs/blob/main/system-stubs-jupiter/src/test/java/uk/org/webcompere/systemstubs/jupiter/examples/SpringAppWithDynamicPropertiesTest.java#L36

This controls the lifecycle of the environment variables BEFORE Spring ever gets a chance to decide how to build a context.

You might get lucky by putting `@ExtendWith(SystemStubsExtension.class)` before `@SpringBootTest`, but I prefer the above pattern.

Alternatively, you can manually execute the `setup()` and `teardown()` methods on `EnvironmentVariable` so that the static initializer of the class turns on the configuration, and then the `@AfterAll` turns it off. I'd avoid that.

One last thing to bear in mind, the demonstrated pattern is especially useful when you're making resources on temp ports and you want spring to know about them through either environment variables or system properties. You initialize test resources in the outer test, which then delegates to the inner `@SpringBootTest` when everything's all set up right.

**Comment by spartanhooah** [comment]
Ok, thanks for all the information. I'll look into your suggestions.
