### ISSUE TITLE
Environment variables not cleared after execute method

### ISSUE THREAD

**Issue by peter-janssen** [webcompere/system-stubs#47]
According to the documentation:
> It should not be necessary to use setup and teardown as the execute method handles this more cleanly, avoiding accidentally leaving the stubbing active
However, this is not what I observe given the following example:
```java
void test() {
    environmentVariables.execute(() -> {
        softly.assertThat(System.getenv().containsKey(KEY)).withFailMessage("Environment variable should be set inside execute method").isTrue();
        softly.assertThat(classUnderTest.getEnvironmentProperties().containsKey(KEY)).withFailMessage("Environment variable should be retrieved from spring").isTrue();
    });
    softly.assertThat(System.getenv().containsKey(KEY)).withFailMessage("Environment variable should be cleared after execute method").isFalse();
    environmentVariables.teardown();
    softly.assertThat(System.getenv().containsKey(KEY)).withFailMessage("Environment variable should definitely be cleared after teardown").isFalse();
}
```
**Expected behaviour**
This test should succeed and the teardown should not be required

**Observed behaviour**
The test fails on the assertion before the teardown

**Resources**
~~Working example can be found [here](https://github.com/peter-janssen/system-stubs-bug)~~

**Comment by ashleyfrieze** [comment]
Thanks for this very thorough bug report @peter-janssen 

You're attempting to use two techniques simultaneously here. SystemStubs was a rewrite of https://github.com/stefanbirkner/system-lambda - it inherits the techniques from that library, which ONLY provided the wrapper pattern:

```
someWrapper.execute(() => {
   // the stub is active here
});
// and not here
```

What SystemStubs adds is the ability for these wrapper objects to be used without the wrapper pattern, even though the wrapper pattern is still available.

So, if you're using them independently of the wrapper pattern, what happens when you ALSO use the wrapper?

In that instance, the stub is activated and deactivated a **second time** within the lifecycle... Internally, it uses reference counting to avoid some surprises...

So when you declare `@SystemStub` on the property of the test fixture and the SystemStubs extension, you're asking SystemStubs to do the setup/teardown of the `EnvironmentVariables` object. As such, it's active for the entire duration of the test class this case (you made it `static`, so it lasts the whole test fixture's lifetime). So, any `execute` you also call on that stub takes from _active_ to _active + 1_ and then back to _active_ again.

I'm afraid this is a mismatch of your assumptions.

However, if you'd like to suggest document changes to help avoid future misunderstanding, please do.

**Comment by peter-janssen** [comment]
Thanks for the rapid response, you are correct that I misunderstood the documentation. Although I could have known because of this remark from the bealdung article:

> When the only available tool is the [execute-around pattern](https://java-design-patterns.com/patterns/execute-around/), it's impossible to hook in the stubbing behavior to all parts of the test lifecycle. This is particularly challenging when trying to combine it with other JUnit extensions, like @SpringBootTest.

And even the static lifecycle was mentioned:

> We can also make our fields static for them to be managed as part of the @BeforeAll/@AfterAll lifecycle.

There is one thing I did have to figure out myself. When dealing with environment variables in the spring context they need to be set in the `@BeforeAll` method. `@BeforeEach` or in the test method will not suffice as the context has already been loaded, hence the static stub.

Writing good documentation is hard especially if it is read quickly, sorry for that ;-). What tripped me up, I think, is the single page layout. This is true for the README.md and the bealdung article. It switches back and forth between the execute around pattern and the stubs. So an improvement could be breaking it up in several pages splitting between junit version and the pattern. But I don't want to impose this kind of effort to anyone (dealing with it myself on other projects). Personally I would have benefitted from a tailored spring(-boot) example.
That being said the documentation is better than most. Combined with the quick response on the issue. All-in-all a great experience using the library. Would recommend it to anyone!

Update:
Looking through the libraries tests I found this [gem](https://github.com/webcompere/system-stubs/blob/93db7a102bb92c832561e251b15caa747eb1c4a6/system-stubs-jupiter/src/test/java/uk/org/webcompere/systemstubs/jupiter/examples/SpringAppWithDynamicPropertiesTest.java#L55)
 ```
// this is setting an environment variable to override a Spring
// property `server.url`. We could similarly use the `SystemProperties`
// object to set `server.url` - but this approach is slightly more challenging,
// so it a more interesting example.
// Only this technique can set environment variables before ANY spring resources
// start up. This could, therefore, be used to override system settings like
// https_proxy, picked up by SDKs in use in the spring application
environmentVariables.set("SERVER_URL", wireMock.baseUrl());
```
